# Generated by Django 4.1.5 on 2023-04-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("getdata", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Conflicts",
        ),
    ]
